//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/Scripts/BuildMode/BuilderInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/BuildMode/BuilderInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @BuilderInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @BuilderInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""BuilderInputs"",
    ""maps"": [
        {
            ""name"": ""builder"",
            ""id"": ""86a1c836-6b3f-4af6-9f2a-0b530d6eb86e"",
            ""actions"": [
                {
                    ""name"": ""OnClicked"",
                    ""type"": ""Button"",
                    ""id"": ""d60f8f79-0243-4f43-9a79-4cff917a25e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnHold"",
                    ""type"": ""Button"",
                    ""id"": ""21db327e-b2e9-46e1-abfe-02bf940efb96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnAction"",
                    ""type"": ""Button"",
                    ""id"": ""17ab5bb6-0ed9-4b1a-b530-543dd5e81e48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnExit"",
                    ""type"": ""Button"",
                    ""id"": ""5ab808e9-5ca5-4eab-9d3e-b439c0041aab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnMoved"",
                    ""type"": ""Value"",
                    ""id"": ""a7e225c2-94ad-4c8b-be78-490ded8911ff"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnRightClick"",
                    ""type"": ""Button"",
                    ""id"": ""9e131e5e-1042-49f7-ab44-87915dead8fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ecc492a-3f73-467c-b4fa-849f8c17160d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""132981ea-b3aa-4fba-afec-162a7150467c"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ff5dc11-8b24-4dff-80fc-9ffa0977e7e1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""734fcab0-f1fd-4d7c-a5ec-ce1c612cf24b"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb4795db-8072-4d21-852b-bba65002a863"",
                    ""path"": ""<Keyboard>/#(P)"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0de65f5a-6c9a-4013-b93b-7c4eaef0ad39"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bf33617-ca3c-4494-adab-6c9bc664c78c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6415d5b-ef35-465f-9a8e-fc9c4604cf45"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0b81207-f3e5-45f4-92c0-52c8d0fd82b7"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMoved"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b49104f-5a8d-4dce-9a07-bf68f1171584"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMoved"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42562d38-fa00-4918-87a3-acf8d2a936dc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnRightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""camera"",
            ""id"": ""ac5cb6cd-b88f-4d52-a19b-bcb95a7c1c2d"",
            ""actions"": [
                {
                    ""name"": ""zoom"",
                    ""type"": ""Value"",
                    ""id"": ""d2885748-1320-4889-ad56-0838ccfc6e42"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""d7431411-606b-4eb2-8ea5-937269d05071"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rotate"",
                    ""type"": ""Value"",
                    ""id"": ""ebc1dcf0-fb82-44f8-9335-ae8d6aa52d6e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""yaw"",
                    ""type"": ""Value"",
                    ""id"": ""4bb328b1-404b-48df-8df6-9a42ac06c31c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch0"",
                    ""type"": ""Value"",
                    ""id"": ""27c8654d-6035-466d-87e4-9d28c4ac58c2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch0_Activated"",
                    ""type"": ""Button"",
                    ""id"": ""7bd8e000-4489-4d79-a713-c1e17a27b6f9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1"",
                    ""type"": ""Value"",
                    ""id"": ""ff66d8ff-fe1b-4aa0-9bdd-20007cdca6da"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1_Activated"",
                    ""type"": ""Button"",
                    ""id"": ""28b0cd74-2d9f-4cb1-86b3-a3a4b620471e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StopMove"",
                    ""type"": ""Button"",
                    ""id"": ""fac21c01-dabd-4ef9-82b2-52702794d392"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b4b46525-fbf1-4cf1-b52d-9b633fa5d755"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e2adb581-db63-4979-a290-0e810f8ae2f0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3bc93c92-7a28-406d-831a-6f2d2d844f58"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=50)"",
                    ""groups"": """",
                    ""action"": ""zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4bc11598-93ae-4b7b-bcc1-9bdccfb8c71d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=50)"",
                    ""groups"": """",
                    ""action"": ""zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MouseSystem"",
                    ""id"": ""848aad5e-a65b-4bc8-9f98-9d34f38e4856"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""65a78445-ddaf-456d-b78c-88f7593e5fcf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""460ca82c-557c-4c02-b59c-387a45b55c02"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5c1f39c1-bc4f-4e76-b6dc-49221ff5f7dd"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2"",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MouseSystem"",
                    ""id"": ""0f2f96c7-ac92-42c7-8984-38ea9d1ea306"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1dfa82f1-0848-4270-abeb-089da9136a4e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""8ddb2929-adb3-4579-abf8-778964d3e467"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ControllerSystem"",
                    ""id"": ""470396d5-4e0b-4f83-b53d-bd9acf081e96"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""6800dc8c-cb41-4545-a357-6e1ebb290241"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""2c3c4c0a-fe5b-4877-870d-fe3eac7a73c4"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MouseSystem"",
                    ""id"": ""a20da618-115a-4612-998a-bdbc3ed4d6c1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""08bdcdf4-e1cf-49a1-bc55-65def5ec5700"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b2abb568-76e9-4194-bb5c-9a8d3350bf45"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ControllerSystem"",
                    ""id"": ""abcb9b60-da04-466e-83c7-bf977fc9512b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""6dbcf4b3-36d7-45a8-ab9d-ba9cd19fa7ae"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""be85f7eb-094e-4fdc-8fc5-cfbb00e18207"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4fd6b8a9-50ce-4be0-bc96-e14c7d049b07"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7a5f67b-b030-48c1-9438-1fe5e6422d28"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c697032b-7263-40eb-a6f2-468ceac68f65"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0_Activated"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0baa164-5241-4623-852d-f4ad0ccba992"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a211d17d-317a-45fa-81c4-204b619731bb"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1_Activated"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68b70631-37fe-4baf-8c37-1ac662756d4d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // builder
        m_builder = asset.FindActionMap("builder", throwIfNotFound: true);
        m_builder_OnClicked = m_builder.FindAction("OnClicked", throwIfNotFound: true);
        m_builder_OnHold = m_builder.FindAction("OnHold", throwIfNotFound: true);
        m_builder_OnAction = m_builder.FindAction("OnAction", throwIfNotFound: true);
        m_builder_OnExit = m_builder.FindAction("OnExit", throwIfNotFound: true);
        m_builder_OnMoved = m_builder.FindAction("OnMoved", throwIfNotFound: true);
        m_builder_OnRightClick = m_builder.FindAction("OnRightClick", throwIfNotFound: true);
        // camera
        m_camera = asset.FindActionMap("camera", throwIfNotFound: true);
        m_camera_zoom = m_camera.FindAction("zoom", throwIfNotFound: true);
        m_camera_move = m_camera.FindAction("move", throwIfNotFound: true);
        m_camera_rotate = m_camera.FindAction("rotate", throwIfNotFound: true);
        m_camera_yaw = m_camera.FindAction("yaw", throwIfNotFound: true);
        m_camera_Touch0 = m_camera.FindAction("Touch0", throwIfNotFound: true);
        m_camera_Touch0_Activated = m_camera.FindAction("Touch0_Activated", throwIfNotFound: true);
        m_camera_Touch1 = m_camera.FindAction("Touch1", throwIfNotFound: true);
        m_camera_Touch1_Activated = m_camera.FindAction("Touch1_Activated", throwIfNotFound: true);
        m_camera_StopMove = m_camera.FindAction("StopMove", throwIfNotFound: true);
    }

    ~@BuilderInputs()
    {
        UnityEngine.Debug.Assert(!m_builder.enabled, "This will cause a leak and performance issues, BuilderInputs.builder.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_camera.enabled, "This will cause a leak and performance issues, BuilderInputs.camera.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // builder
    private readonly InputActionMap m_builder;
    private List<IBuilderActions> m_BuilderActionsCallbackInterfaces = new List<IBuilderActions>();
    private readonly InputAction m_builder_OnClicked;
    private readonly InputAction m_builder_OnHold;
    private readonly InputAction m_builder_OnAction;
    private readonly InputAction m_builder_OnExit;
    private readonly InputAction m_builder_OnMoved;
    private readonly InputAction m_builder_OnRightClick;
    /// <summary>
    /// Provides access to input actions defined in input action map "builder".
    /// </summary>
    public struct BuilderActions
    {
        private @BuilderInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BuilderActions(@BuilderInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "builder/OnClicked".
        /// </summary>
        public InputAction @OnClicked => m_Wrapper.m_builder_OnClicked;
        /// <summary>
        /// Provides access to the underlying input action "builder/OnHold".
        /// </summary>
        public InputAction @OnHold => m_Wrapper.m_builder_OnHold;
        /// <summary>
        /// Provides access to the underlying input action "builder/OnAction".
        /// </summary>
        public InputAction @OnAction => m_Wrapper.m_builder_OnAction;
        /// <summary>
        /// Provides access to the underlying input action "builder/OnExit".
        /// </summary>
        public InputAction @OnExit => m_Wrapper.m_builder_OnExit;
        /// <summary>
        /// Provides access to the underlying input action "builder/OnMoved".
        /// </summary>
        public InputAction @OnMoved => m_Wrapper.m_builder_OnMoved;
        /// <summary>
        /// Provides access to the underlying input action "builder/OnRightClick".
        /// </summary>
        public InputAction @OnRightClick => m_Wrapper.m_builder_OnRightClick;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_builder; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BuilderActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BuilderActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BuilderActions" />
        public void AddCallbacks(IBuilderActions instance)
        {
            if (instance == null || m_Wrapper.m_BuilderActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuilderActionsCallbackInterfaces.Add(instance);
            @OnClicked.started += instance.OnOnClicked;
            @OnClicked.performed += instance.OnOnClicked;
            @OnClicked.canceled += instance.OnOnClicked;
            @OnHold.started += instance.OnOnHold;
            @OnHold.performed += instance.OnOnHold;
            @OnHold.canceled += instance.OnOnHold;
            @OnAction.started += instance.OnOnAction;
            @OnAction.performed += instance.OnOnAction;
            @OnAction.canceled += instance.OnOnAction;
            @OnExit.started += instance.OnOnExit;
            @OnExit.performed += instance.OnOnExit;
            @OnExit.canceled += instance.OnOnExit;
            @OnMoved.started += instance.OnOnMoved;
            @OnMoved.performed += instance.OnOnMoved;
            @OnMoved.canceled += instance.OnOnMoved;
            @OnRightClick.started += instance.OnOnRightClick;
            @OnRightClick.performed += instance.OnOnRightClick;
            @OnRightClick.canceled += instance.OnOnRightClick;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BuilderActions" />
        private void UnregisterCallbacks(IBuilderActions instance)
        {
            @OnClicked.started -= instance.OnOnClicked;
            @OnClicked.performed -= instance.OnOnClicked;
            @OnClicked.canceled -= instance.OnOnClicked;
            @OnHold.started -= instance.OnOnHold;
            @OnHold.performed -= instance.OnOnHold;
            @OnHold.canceled -= instance.OnOnHold;
            @OnAction.started -= instance.OnOnAction;
            @OnAction.performed -= instance.OnOnAction;
            @OnAction.canceled -= instance.OnOnAction;
            @OnExit.started -= instance.OnOnExit;
            @OnExit.performed -= instance.OnOnExit;
            @OnExit.canceled -= instance.OnOnExit;
            @OnMoved.started -= instance.OnOnMoved;
            @OnMoved.performed -= instance.OnOnMoved;
            @OnMoved.canceled -= instance.OnOnMoved;
            @OnRightClick.started -= instance.OnOnRightClick;
            @OnRightClick.performed -= instance.OnOnRightClick;
            @OnRightClick.canceled -= instance.OnOnRightClick;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BuilderActions.UnregisterCallbacks(IBuilderActions)" />.
        /// </summary>
        /// <seealso cref="BuilderActions.UnregisterCallbacks(IBuilderActions)" />
        public void RemoveCallbacks(IBuilderActions instance)
        {
            if (m_Wrapper.m_BuilderActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BuilderActions.AddCallbacks(IBuilderActions)" />
        /// <seealso cref="BuilderActions.RemoveCallbacks(IBuilderActions)" />
        /// <seealso cref="BuilderActions.UnregisterCallbacks(IBuilderActions)" />
        public void SetCallbacks(IBuilderActions instance)
        {
            foreach (var item in m_Wrapper.m_BuilderActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuilderActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BuilderActions" /> instance referencing this action map.
    /// </summary>
    public BuilderActions @builder => new BuilderActions(this);

    // camera
    private readonly InputActionMap m_camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_camera_zoom;
    private readonly InputAction m_camera_move;
    private readonly InputAction m_camera_rotate;
    private readonly InputAction m_camera_yaw;
    private readonly InputAction m_camera_Touch0;
    private readonly InputAction m_camera_Touch0_Activated;
    private readonly InputAction m_camera_Touch1;
    private readonly InputAction m_camera_Touch1_Activated;
    private readonly InputAction m_camera_StopMove;
    /// <summary>
    /// Provides access to input actions defined in input action map "camera".
    /// </summary>
    public struct CameraActions
    {
        private @BuilderInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CameraActions(@BuilderInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "camera/zoom".
        /// </summary>
        public InputAction @zoom => m_Wrapper.m_camera_zoom;
        /// <summary>
        /// Provides access to the underlying input action "camera/move".
        /// </summary>
        public InputAction @move => m_Wrapper.m_camera_move;
        /// <summary>
        /// Provides access to the underlying input action "camera/rotate".
        /// </summary>
        public InputAction @rotate => m_Wrapper.m_camera_rotate;
        /// <summary>
        /// Provides access to the underlying input action "camera/yaw".
        /// </summary>
        public InputAction @yaw => m_Wrapper.m_camera_yaw;
        /// <summary>
        /// Provides access to the underlying input action "camera/Touch0".
        /// </summary>
        public InputAction @Touch0 => m_Wrapper.m_camera_Touch0;
        /// <summary>
        /// Provides access to the underlying input action "camera/Touch0_Activated".
        /// </summary>
        public InputAction @Touch0_Activated => m_Wrapper.m_camera_Touch0_Activated;
        /// <summary>
        /// Provides access to the underlying input action "camera/Touch1".
        /// </summary>
        public InputAction @Touch1 => m_Wrapper.m_camera_Touch1;
        /// <summary>
        /// Provides access to the underlying input action "camera/Touch1_Activated".
        /// </summary>
        public InputAction @Touch1_Activated => m_Wrapper.m_camera_Touch1_Activated;
        /// <summary>
        /// Provides access to the underlying input action "camera/StopMove".
        /// </summary>
        public InputAction @StopMove => m_Wrapper.m_camera_StopMove;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_camera; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CameraActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CameraActions" />
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @zoom.started += instance.OnZoom;
            @zoom.performed += instance.OnZoom;
            @zoom.canceled += instance.OnZoom;
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @rotate.started += instance.OnRotate;
            @rotate.performed += instance.OnRotate;
            @rotate.canceled += instance.OnRotate;
            @yaw.started += instance.OnYaw;
            @yaw.performed += instance.OnYaw;
            @yaw.canceled += instance.OnYaw;
            @Touch0.started += instance.OnTouch0;
            @Touch0.performed += instance.OnTouch0;
            @Touch0.canceled += instance.OnTouch0;
            @Touch0_Activated.started += instance.OnTouch0_Activated;
            @Touch0_Activated.performed += instance.OnTouch0_Activated;
            @Touch0_Activated.canceled += instance.OnTouch0_Activated;
            @Touch1.started += instance.OnTouch1;
            @Touch1.performed += instance.OnTouch1;
            @Touch1.canceled += instance.OnTouch1;
            @Touch1_Activated.started += instance.OnTouch1_Activated;
            @Touch1_Activated.performed += instance.OnTouch1_Activated;
            @Touch1_Activated.canceled += instance.OnTouch1_Activated;
            @StopMove.started += instance.OnStopMove;
            @StopMove.performed += instance.OnStopMove;
            @StopMove.canceled += instance.OnStopMove;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CameraActions" />
        private void UnregisterCallbacks(ICameraActions instance)
        {
            @zoom.started -= instance.OnZoom;
            @zoom.performed -= instance.OnZoom;
            @zoom.canceled -= instance.OnZoom;
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @rotate.started -= instance.OnRotate;
            @rotate.performed -= instance.OnRotate;
            @rotate.canceled -= instance.OnRotate;
            @yaw.started -= instance.OnYaw;
            @yaw.performed -= instance.OnYaw;
            @yaw.canceled -= instance.OnYaw;
            @Touch0.started -= instance.OnTouch0;
            @Touch0.performed -= instance.OnTouch0;
            @Touch0.canceled -= instance.OnTouch0;
            @Touch0_Activated.started -= instance.OnTouch0_Activated;
            @Touch0_Activated.performed -= instance.OnTouch0_Activated;
            @Touch0_Activated.canceled -= instance.OnTouch0_Activated;
            @Touch1.started -= instance.OnTouch1;
            @Touch1.performed -= instance.OnTouch1;
            @Touch1.canceled -= instance.OnTouch1;
            @Touch1_Activated.started -= instance.OnTouch1_Activated;
            @Touch1_Activated.performed -= instance.OnTouch1_Activated;
            @Touch1_Activated.canceled -= instance.OnTouch1_Activated;
            @StopMove.started -= instance.OnStopMove;
            @StopMove.performed -= instance.OnStopMove;
            @StopMove.canceled -= instance.OnStopMove;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CameraActions.UnregisterCallbacks(ICameraActions)" />.
        /// </summary>
        /// <seealso cref="CameraActions.UnregisterCallbacks(ICameraActions)" />
        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CameraActions.AddCallbacks(ICameraActions)" />
        /// <seealso cref="CameraActions.RemoveCallbacks(ICameraActions)" />
        /// <seealso cref="CameraActions.UnregisterCallbacks(ICameraActions)" />
        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CameraActions" /> instance referencing this action map.
    /// </summary>
    public CameraActions @camera => new CameraActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "builder" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BuilderActions.AddCallbacks(IBuilderActions)" />
    /// <seealso cref="BuilderActions.RemoveCallbacks(IBuilderActions)" />
    public interface IBuilderActions
    {
        /// <summary>
        /// Method invoked when associated input action "OnClicked" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnClicked(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnExit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnExit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnMoved" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnMoved(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OnRightClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnRightClick(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "camera" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CameraActions.AddCallbacks(ICameraActions)" />
    /// <seealso cref="CameraActions.RemoveCallbacks(ICameraActions)" />
    public interface ICameraActions
    {
        /// <summary>
        /// Method invoked when associated input action "zoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoom(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "rotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "yaw" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYaw(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch0_Activated" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch0_Activated(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch1_Activated" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch1_Activated(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StopMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStopMove(InputAction.CallbackContext context);
    }
}
